# Site wide configuration

title: Olin College - Huang Lab
description: "An Online Guide for Olin College Students"
logo: 120x120.gif
teaser: main3.jpg
locale: en_US
url: //HuangLab.github.io/Bioinformatics

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Pinar Demetci
  web: http://pinardemetci.com
  email: pinardemetci@gmail.com
  twitter: Pinar_dem
  bio: "Bioengineering student."
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: +PinarDemetci
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
